defaults:
  - _self_

pretrained_model_name_or_path: null
controlnet_model_name_or_path: null
revision: null
variant: null
tokenizer_name: null
output_dir: controlnet-model
cache_dir: null
seed: null
resolution: 512
train_batch_size: 4
num_train_epochs: 1
max_train_steps: null
checkpointing_steps: 500
checkpoints_total_limit: null
resume_from_checkpoint: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 5e-6
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: false
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: logs
allow_tf32: false
report_to: tensorboard
mixed_precision: null
enable_xformers_memory_efficient_attention: false
set_grads_to_none: false
dataset_name: null
dataset_config_name: null
train_data_dir: null
image_column: image
conditioning_image_column: conditioning_image
caption_column: text
max_train_samples: null
proportion_empty_prompts: 0.0
validation_prompt: null
validation_image: null
num_validation_images: 4
validation_steps: 100
tracker_project_name: train_controlnet