paths:
  input_masks_path: "$bdd_dataset_path/bdd/bdd100k/labels/sem_seg/colormaps/val" 
  base_model_path: "stabilityai/stable-diffusion-xl-base-1.0"
  controlnet_path: "$repo_root/runs/checkpoint-10000/controlnet"
  attach_images_path: '$bdd_dataset_path/bdd/bdd100k/images/10k/train/' #original reference images
  infer_path: '$repo_root/infer_out_10000'

mask_bg_color: [0,0,0]  # semseg mask color, on generated images this spot should be filled
mask_ego_color: [0,0,0] # semseg mask color, on generated images this spot should be filled
limit: 100
guidance_scale: 3 
prompt: "Traffic scene. Outside. Daytime. Sky. High resolution."

resolution:
  width: 1280
  height: 720
negative_prompt: "cartoon"
num_generations: 2 # generate this many images for a single input mask
attach_reference_image: True # attach the reference image to the output grids